import React from 'react';
import Head from 'next/head';
import Navbar from './navbar';
import ThemeContext from '../contexts/ThemeContext';
import styles from '../styles/Layout.module.css';
import Image from 'next/image';

export default function Layout({ children }) {
  const { theme } = React.useContext(ThemeContext);
  return (
    <div className={theme}>
      <div className='container'>
        <Head>
          <title>Hacker News with NextJS</title>
          <meta
            name='Hacker News with NextJS'
            content='Generated by create next app'
          />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className={styles.container}>
          <Navbar />
          <main>{children}</main>
        </div>
        <footer className={styles.footer}>
          <a
            href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src='/vercel.svg'
                alt='Vercel Logo'
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </div>
  );
}
